export const KafkaEvents = {
  DISPUTE_CREATED: 'DISPUTE_CREATED',
  DISPUTE_UNDER_REVIEW: 'DISPUTE_UNDER_REVIEW',
  DISPUTE_RESOLVED: 'DISPUTE_RESOLVED',
  ESCROW_CREATED: 'ESCROW_CREATED',
  ESCROW_PAYMENT_INITIATED: 'ESCROW_PAYMENT_INITIATED',
  ESCROW_DEADLINE_EXTENDED: 'ESCROW_DEADLINE_EXTENDED',
  ESCROW_FUNDED: 'ESCROW_FUNDED',
  ESCROW_COMPLETED: 'ESCROW_COMPLETED',
  ESCROW_RELEASED: 'ESCROW_RELEASED',
  ESCROW_REFUNDED: 'ESCROW_REFUNDED',
};
